### ISSUE TITLE
Cannot get query locator from response of 'getBulkqueryResults' method

### ISSUE THREAD

**Issue by avesolovksyy** [msrivastav13/node-sf-bulk2#10]
When fetching query results method **getBulkqueryResults** returns back only text body of the response. But we are also interested in getting back locator, which is part of response headers named **Sforce-Locator** (as described [here](https://developer.salesforce.com/docs/atlas.en-us.api_bulk_v2.meta/api_bulk_v2/query_get_job_results.htm) in example section) to get next portion of result data set.

Also we've noticed that in **getBulkqueryResults** method signature **locator** is declared as 'number', while actually it should be 'string' (again referring to the same example in doc above).

**Comment by msrivastav13** [comment]
@avesolovksyy Thanks for reporting. Released 0.20.22 version. This should have the fix.

Here is what you will need to do,

`const results: AxiosResponse = await getBulkQueryResults(jobid, locator, maxresults);`
  ` console.log(results.data); // This has data`
  ` console.log(results.headers); // This has header`

Let me know if you still face any issues with this.

**Comment by avesolovksyy** [comment]
@msrivastav13 

Yep, works like a charm, thanks.
Closing this one.

P.S.
You may consider implementing also a high level function for end-to-end use case - to take a query as input param and return whole set of results (i.e. doing all these steps under the hood: submit query -> wait for job to complete -> fetch all chunks of results and output into a single file). To make it even simpler, sort of bulk api v3.0)
