### ISSUE TITLE
What should be the next step on SFDC?

### ISSUE THREAD

**Issue by nsantullo** [msrivastav13/node-sf-bulk2#17]
HI,
I used the npm module bulk2 and I everything went well.
I would like to know what should i look for on SFDC? I cannot see the account created. Is there any job processing on salesforce sdie?
thank you

**Comment by msrivastav13** [comment]
Go to the bulk jobs in the set up and see if jobs were success.

**Comment by nsantullo** [comment]
Thanks a lot.
On SFDC side I'm getting the following ? Do you have any hints?
null:InvalidBatch : InvalidBatch : Field name not found : ﻿Name. Batch will not be retried.

My csv file looks like this:
Name,Description,NumberOfEmployees
TestAccount4,Description of TestAccount1,30
TestAccount5,Another description,40
TestAccount6,Yet another description,50

Thank you!
